name: numpy_to_jax
channels:
  - defaults
dependencies:
  - anyio=4.2.0=py312hca03da5_0
  - appnope=0.1.3=py312hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h80987f9_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py312hca03da5_0
  - attrs=23.1.0=py312hca03da5_0
  - babel=2.11.0=py312hca03da5_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py312hca03da5_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.7=py312ha86b861_0
  - brotli-python=1.0.9=py312h313beb8_7
  - bzip2=1.0.8=h80987f9_5
  - ca-certificates=2024.3.11=hca03da5_0
  - certifi=2024.2.2=py312hca03da5_0
  - cffi=1.16.0=py312h80987f9_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.2.1=py312hca03da5_0
  - cryptography=42.0.5=py312hd4332d6_0
  - debugpy=1.6.7=py312h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py312hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=h313beb8_0
  - idna=3.4=py312hca03da5_0
  - importlib-metadata=7.0.1=py312hca03da5_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - ipykernel=6.28.0=py312hca03da5_0
  - ipython=8.20.0=py312hca03da5_0
  - jedi=0.18.1=py312hca03da5_1
  - jinja2=3.1.3=py312hca03da5_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py312hca03da5_0
  - jsonschema-specifications=2023.7.1=py312hca03da5_0
  - jupyter-lsp=2.2.0=py312hca03da5_0
  - jupyter_client=8.6.0=py312hca03da5_0
  - jupyter_core=5.5.0=py312hca03da5_0
  - jupyter_events=0.8.0=py312hca03da5_0
  - jupyter_server=2.10.0=py312hca03da5_0
  - jupyter_server_terminals=0.4.4=py312hca03da5_1
  - jupyterlab=4.0.11=py312hca03da5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py312hca03da5_0
  - libcxx=14.0.6=h848a8c0_0
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.21=h269037a_0
  - libsodium=1.0.18=h1a28f6b_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - markupsafe=2.1.3=py312h80987f9_0
  - matplotlib-inline=0.1.6=py312hca03da5_0
  - mistune=2.0.4=py312hca03da5_0
  - nbclient=0.8.0=py312hca03da5_0
  - nbconvert=7.10.0=py312hca03da5_0
  - nbformat=5.9.2=py312hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py312hca03da5_0
  - notebook=7.0.8=py312hca03da5_0
  - notebook-shim=0.2.3=py312hca03da5_0
  - numexpr=2.8.7=py312h0f3ea24_0
  - numpy=1.26.4=py312h7f4fdc5_0
  - numpy-base=1.26.4=py312he047099_0
  - openssl=3.0.13=h1a28f6b_0
  - overrides=7.4.0=py312hca03da5_0
  - packaging=23.2=py312hca03da5_0
  - pandas=2.2.1=py312hd77ebd4_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.3.1=py312hca03da5_0
  - platformdirs=3.10.0=py312hca03da5_0
  - prometheus_client=0.14.1=py312hca03da5_0
  - prompt-toolkit=3.0.43=py312hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py312h80987f9_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py312hca03da5_1
  - pyopenssl=24.0.0=py312hca03da5_0
  - pysocks=1.7.1=py312hca03da5_0
  - python=3.12.2=h99e199e_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py312hca03da5_0
  - python-json-logger=2.0.7=py312hca03da5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2023.3.post1=py312hca03da5_0
  - pyyaml=6.0.1=py312h80987f9_0
  - pyzmq=25.1.2=py312h313beb8_0
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py312hca03da5_0
  - requests=2.31.0=py312hca03da5_1
  - rfc3339-validator=0.1.4=py312hca03da5_0
  - rfc3986-validator=0.1.1=py312hca03da5_0
  - rpds-py=0.10.6=py312hf0e4da2_0
  - send2trash=1.8.2=py312hca03da5_0
  - setuptools=68.2.2=py312hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py312hca03da5_0
  - soupsieve=2.5=py312hca03da5_0
  - sqlite=3.41.2=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py312hca03da5_0
  - tinycss2=1.2.1=py312hca03da5_0
  - tk=8.6.12=hb8d0fd4_0
  - tomli=2.0.1=py312hca03da5_1
  - tornado=6.3.3=py312h80987f9_0
  - traitlets=5.7.1=py312hca03da5_0
  - typing-extensions=4.9.0=py312hca03da5_1
  - typing_extensions=4.9.0=py312hca03da5_1
  - tzdata=2024a=h04d1e81_0
  - urllib3=2.1.0=py312hca03da5_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py312hca03da5_2
  - websocket-client=0.58.0=py312hca03da5_4
  - wheel=0.41.2=py312hca03da5_0
  - xz=5.4.6=h80987f9_0
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.17.0=py312hca03da5_0
  - zlib=1.2.13=h5a0b063_0
  - pip:
      - arrow==1.3.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - fonttools==4.51.0
      - fqdn==1.5.1
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - jsonpointer==2.4
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.4.5
      - lab==8.1
      - matplotlib==3.8.4
      - pillow==10.3.0
      - pyparsing==3.1.2
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - simplejson==3.19.2
      - tqdm==4.66.2
      - txt2tags==3.9
      - types-python-dateutil==2.9.0.20240316
      - uri-template==1.3.0
      - webcolors==1.13
      - widgetsnbextension==4.0.10
prefix: /opt/homebrew/anaconda3/envs/numpy_to_jax
