name: numpy_to_jax
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - async-lru
  - attrs
  - babel
  - backcall
  - beautifulsoup4
  - blas
  - bleach
  - bottleneck
  - brotli-python
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - comm
  - cryptography
  - debugpy
  - decorator
  - defusedxml
  - exceptiongroup
  - executing
  - idna
  - importlib-metadata
  - importlib_metadata
  - ipykernel
  - ipython
  - jedi
  - jinja2
  - json5
  - jsonschema
  - jsonschema-specifications
  - jupyter-lsp
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - libcxx
  - libffi
  - libgfortran
  - libgfortran5
  - libopenblas
  - libsodium
  - llvm-openmp
  - markupsafe
  - matplotlib-inline
  - mistune
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - notebook
  - notebook-shim
  - numexpr
  - numpy
  - numpy-base
  - openssl
  - overrides
  - packaging
  - pandas
  - pandocfilters
  - parso
  - pexpect
  - pickleshare
  - pip
  - platformdirs
  - prometheus_client
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pycparser
  - pygments
  - pyopenssl
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python-tzdata
  - pytz
  - pyyaml
  - pyzmq
  - readline
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rpds-py
  - send2trash
  - setuptools
  - six
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - terminado
  - tinycss2
  - tk
  - tomli
  - tornado
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
